#' Add group condition and significance
#'
#' Used for generating dataframe for plotting relative transcript abundances in DTU::plot_genes_cohort()
#' @param alpha double to define alpha for significance threshold. Default is 0.05
#' @param info dataframe holding sample information. Must have all required column names; therefore must be generated by DTU::create_cample_info. Will be used to join the significance information by sample_id. 
#' @param main_df dataframe generated by DTU::stageResPlusInfo, holding all results. 
#' @param countsmelted df from DTU::plot_genes_cohort 
#' @return dataframe to be used in DTU::plot_genes_cohort()
#' @export
#' @importFrom dplyr %>%
#' @importFrom dplyr case_when
#' @importFrom magrittr %<>%
#' @importFrom rlang .data
add_condition_and_sig_tx <- function(alpha=0.05, info, countsmelted, main_df) {
 countsmelted <- dplyr::left_join(countsmelted, info[, c("condition", "sample_id")], by = "sample_id")
 main_df %<>% dplyr::rename(transcript_id = .data$tx_id)
 countsmelted  <-  dplyr::left_join(countsmelted, main_df[, c("transcript_id", "tx_pvalueStageR", "nom_pval")], by="transcript_id")
 countsmelted <- dplyr::left_join(countsmelted, main_df[, c("gene_id", "pval_dge", "padj_dge")] %>% dplyr::distinct(.data$gene_id, .keep_all = T), by = "gene_id")
 countsmelted %<>% dplyr::mutate(sig = case_when(
  grepl("observed", .data$countType) ~ 0,
  grepl("dge", .data$countType) & padj_dge < alpha ~ 1,
  grepl("dge", .data$coun_type) & padj_dge >= alpha ~ 0,
  !(is.na(.data$tx_pvalueStageR)) ~ 1,
  is.na(.data$tx_pvalueStageR) ~ 0
  ), nomSig = case_when(
  grepl("observed", .data$countType) ~ 0,
  grepl("dge", .data$countType) & pval_dge < alpha ~ 1,
  grepl("dge", .data$countType) & pval_dge >= alpha ~ 0,
  nom_pval < alpha ~ 1,
  nom_pval >= alpha ~ 0
  )) %>%
  dplyr::select(.data$countType, .data$gene_id, .data$transcript_id, .data$sample_id, .data$frac, .data$condition, .data$sig, .data$nomSig)
 return(countsmelted)
}
