#' apply tool intersection per cohort
#' 
#' Used in "bindToolRes.R" to put together the tool specific result dataframes which were generated by the pipeline 
#' @param objs_by_cohort : objs listed by cohort and each tool result per cohort (after DTU::split_by_cohorts() was used)
#' @param tx : level of list intersection (TRUE || FALSE ) tx vs gene level, default=T
#' @param tool_idx: which tools to intersect, default:NULL, all tools are being intersected. (Was helpful before when we also used IsoformSwitchAnalyserR. Might become usefull when we try other tools.)
#' @param opt opt parse object that was generated in "bindToolRes.R" when called through bash script "runDTU.sh"
#' @return list with one dataframe per cohort, holding a DTU events (as returned from stageR) that overlap between the tools
#'@export
apply_tool_intersect <- function(objs_by_cohort, tool_idx = NULL, tx = T, opt) {
 if (is.null(tool_idx)) {
  tool_int_genelst_by_cohort <- lapply(seq(1, length(objs_by_cohort)), function(i) {
    if (tx == TRUE) {
     gene_lst <- tryCatch(get_gene_info(simple_intersect(objs_by_cohort[[i]], tx = TRUE), tx = TRUE),
	         error = function(e) {
		 return(NULL)
		})
     }
     else {
      gene_lst <- tryCatch(get_gene_info(simple_intersect(objs_by_cohort[[i]], tx = FALSE), tx = FALSE),
			  error = function(e) {
				  return(NULL)
			  })
    }
      
    utils::write.csv(gene_lst, file = paste0(opt$o, "intersection_genelst_allTools", names(objs_by_cohort)[i], ".csv"), quote = FALSE, row.names = FALSE)
      return(gene_lst)
   })
  }
 else {
  tool_int_genelst_by_cohort <- lapply(seq(1, length(objs_by_cohort)), function(i) {
   if (tx == TRUE) {
    gene_lst <- tryCatch(get_gene_info(simple_intersect(objs_by_cohort[[i]][tool_idx], tx = TRUE), tx = TRUE), error = function(e) {
     return(NULL)})
   } else {
    gene_lst <- tryCatch(get_gene_info(simple_intersect(objs_by_cohort[[i]][tool_idx], tx = FALSE), tx = FALSE), error = function(e) {
     return(NULL)})
    }
   cohort <- names(objs_by_cohort)[i]
   tools <- paste(names(objs_by_cohort[[cohort]])[tool_idx], collapse = "_")
   tools <- base::gsub("_gene_lsts", "", tools)
   utils::write.csv(gene_lst, file = paste0(opt$o, "intersection_genelst_", tools, "_", cohort, ".csv"), quote = FALSE, row.names = FALSE)
   return(gene_lst)
   })
 }
 names(tool_int_genelst_by_cohort) <- names(objs_by_cohort)
 return(tool_int_genelst_by_cohort)
}
